[package]
name = "gutmann"
version = "0.1.0"
authors = ["Robin Lindner <robin@deeprobin.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.3"